language: python
python:
- "3.7"
# setup environment
env:
- DJANGO_VERSION=3.1.5
- DJANGO_SETTINGS_MODULE='UKS.settings'
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python src/manage.py test 


if: (type = pull_request AND branch == dev)