language: sh
python:
  - "3.6"
before_install:
      - choco install python3
      - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
# command to install dependencies
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test
os:
  - windows

# branches:
#   only:
#     - master

if: (type = push AND branch IN (feature/travis, dev)) OR (type = pull_request AND branch == dev)