language: python

python:
  - "3.6"

# services: postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt

# before_script:
#   - psql -c 'create database uks;' -U postgres

# test:
#   adapter: postgresql
#   database: uks

# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test

if: (type = pull_request AND branch == dev)
