os: windows
language: sh
python: '3.6'
before_install:
  - choco install python --version 3.6.0
  - easy_install --upgrade pip
  # - wget https://bootstrap.pypa.io/2.7/get-pip.py
  # - python get-pip.py
install:
  - pip install -r requirements.txt
env:
  - DJANGO_VERSION=3.1.5
script:
  - python manage.py test
if: (type = pull_request AND branch == dev)
