# Generated by Django 3.1.1 on 2021-01-05 15:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wiki_wikiversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
