# Generated by Django 3.1.1 on 2021-01-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_wiki_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiversion',
            name='wiki',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.wiki'),
        ),
    ]
