# Generated by Django 3.1.5 on 2021-01-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_task_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskversion',
            name='taskState',
            field=models.CharField(blank=True, choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Review', 'Review'), ('Done', 'Done')], default='To do', max_length=255, null=True),
        ),
    ]
