# Generated by Django 3.1.5 on 2021-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210118_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskversion',
            name='taskState',
            field=models.CharField(blank=True, choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('REVIEW', 'Review'), ('DONE', 'Done')], default='TO_DO', max_length=255, null=True),
        ),
    ]
