# Generated by Django 3.1.5 on 2021-01-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210118_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskversion',
            old_name='taskState',
            new_name='task_state',
        ),
    ]
