# Generated by Django 3.1.5 on 2021-01-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210118_1257'),
        ('app', '0008_organization_members'),
    ]

    operations = [
    ]
