# Generated by Django 3.1.5 on 2021-02-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_changehistory'),
        ('app', '0017_commit'),
    ]

    operations = [
    ]
